import { registerDeliveryAction } from '../../delivery.js';
import { handleAddDestination } from './add-destination.js';
import { handleCreateGroup } from './create-group.js';
import { handleProvisionChildBoard } from './provision-child-board.js';
import { handleProvisionRootBoard } from './provision-root-board.js';
import { handleRenameBoardPerson } from './rename-board-person.js';
import { handleTaskflowDispatchNotifications } from './taskflow-dispatch.js';
import { handleTaskflowNotify } from './taskflow-notify.js';
import { handleTaskflowWebChatInbound } from './taskflow-web-chat-inbound.js';
import { handleTaskflowWebChatReply } from './taskflow-web-chat-reply.js';

registerDeliveryAction('provision_root_board', handleProvisionRootBoard);
registerDeliveryAction('provision_child_board', handleProvisionChildBoard);
registerDeliveryAction('rename_board_person', handleRenameBoardPerson);
registerDeliveryAction('create_group', handleCreateGroup);
registerDeliveryAction('add_destination', handleAddDestination);
registerDeliveryAction('taskflow_notify', handleTaskflowNotify);
registerDeliveryAction('taskflow_dispatch_notifications', handleTaskflowDispatchNotifications);
registerDeliveryAction('taskflow_web_chat_inbound', handleTaskflowWebChatInbound);
registerDeliveryAction('taskflow_web_chat_reply', handleTaskflowWebChatReply);
